name: Backend checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.BRANCH }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: backend/build.gradle.kts

      - name: Run Java backend tests
        run: ./gradlew test
        working-directory: backend

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: backend
